name: Test building packages

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install required tools
        run: sudo apt-get install debhelper
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v3
        with: 
          repository: UNICORE-EU/tsi
      - name: build
        run: make all
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: |
            target/*.deb
            target/*.rpm
            target/*.tgz
